### ISSUE TITLE
что за сертификат необходимо указать в параметр $settings->cert? 

### ISSUE THREAD

**Issue by kapitonoval** [shnellpavel/yandex-money-payout#1]
HI.
Подскажите какие именно сертификаты необходимо указать.
Yandex должен выдал только 1 сертификат, где взять второй?

**Comment by shnellpavel** [comment]
Привет. 
Мой ответ, скорее всего очень запоздалый, но всё же:
`$settings->privateKey` - приватный ключ, который необходимо сгенерировать и беречь как зеницу ока. На его основе создаётся запрос на получение сертификата. 
`$settings->certPassword` - пароль к приватному ключу. 
`$settings->cert` - сертификат, полученный от yandex при регистрации.
`$settings->yaCert` - публичный сертификат сервера yandex. Необходим для проверки автора callback-запроса.
